name: "Handle Comment Workflow"
on:
  issue_comment:
    types:
      - created
jobs:
  closed-issue-comment:
    uses: fresh8gaming/cypress-orb/.github/workflows/triage_handle_new_comments.yml@develop
    secrets: inherit
